# adapted from https://github.com/dwyl/learn-travis/issues/31
language: node_js # elm is installed from npm (see install below)
node_js: node     # use "latest" version of Node.js

cache:
  directories: # so subsequent builds run faster
    - $HOME/.npm # https://stackoverflow.com/a/42523517/1148249
    - sysconfcpus

before_install:
    - | # epic build time improvement - see https://github.com/elm-lang/elm-compiler/issues/1473#issuecomment-245704142
      if [ ! -d sysconfcpus/bin ];
      then
        git clone https://github.com/obmarg/libsysconfcpus.git;
        cd libsysconfcpus;
        ./configure --prefix=$TRAVIS_BUILD_DIR/sysconfcpus;
        make && make install;
        cd ..;
      fi

install: # install specific version of elm
  - npm install -g elm@0.19.0 elm-test@0.19.0
  - mv $(npm config get prefix)/bin/elm $(npm config get prefix)/bin/elm-old
  - printf '%s\n\n' '#!/bin/bash' 'echo "Running elm with sysconfcpus -n 1"' '$TRAVIS_BUILD_DIR/sysconfcpus/bin/sysconfcpus -n 1 elm-old "$@"' > $(npm config get prefix)/bin/elm
  - chmod +x $(npm config get prefix)/bin/elm

script:
  - elm-test
